pages/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView

app_name = "pages"

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("", HomePageView.as_view(), name="home"),
]

pysrc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('trees/', include("trees.urls")),
]

if settings.DEBUG: # em produção essa parte devera ser alterada
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

trees/urls.py
from django.urls import path

from .views import TreeDetailView, TreeListView

app_name = "trees"

urlpatterns = [
    path("", TreeListView.as_view(), name="list"),
    path("<slug:slug>/", TreeDetailView.as_view(), name="detail"),
    path("square/<slug:slug>/", TreeListView.as_view(), name="list_by_square"),
]

pages/models.py
from django.db import models

# Create your models here.

trees/models.py
from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel
import uuid

def get_file_path(_instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return filename

class DisplayManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_display=True)


class Square(TimeStampedModel):
    name = models.CharField('Nome', max_length=255, unique=True)
    is_display = models.BooleanField('Exibir', default=True)
    description = models.TextField('Descrição', max_length=200, blank=True) #implementado
    address = models.CharField('Endereço', max_length=255, blank=True)#implementado
    image1 = models.ImageField('imagem 1', upload_to=get_file_path, blank=True)#modificado original não tem 'imagem'
    altimg1 = models.CharField('Alt imagem 1', max_length=150, blank=True)
    image2 = models.ImageField('imagem 2', upload_to=get_file_path, blank=True)
    altimg2 = models.CharField('Alt imagem 2', max_length=150, blank=True)
    image3 = models.ImageField('imagem 3', upload_to=get_file_path, blank=True)
    altimg3 = models.CharField('Alt imagem 3', max_length=150, blank=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")


    objects = models.Manager()
    display = DisplayManager()

    class Meta:
        ordering = ("name",)
        verbose_name = "Praça"
        verbose_name_plural = "Praças"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("trees:list_by_square", kwargs={"slug": self.slug})

class Specie(TimeStampedModel):
    name = models.CharField('Nome', max_length=255, unique=True)
    description = models.TextField('Descrição', blank=True) #implementado

    class Meta:
        ordering = ("name",)
        verbose_name = "Espécie"
        verbose_name_plural = "Espécies"

    def __str__(self):
        return self.name

class Family(TimeStampedModel):
    name = models.CharField('Nome', max_length=255, unique=True)
    description = models.TextField('Descrição', blank=True) #implementado

    class Meta:
        ordering = ("name",)
        verbose_name = "Família"
        verbose_name_plural = "Famílias"

    def __str__(self):
        return self.name



    


class Tree(TimeStampedModel):
    SOURCE_CHOICES = (
        ('nativa', 'Nativa'),
        ('exotica', 'Exótica'),
        ('nativa_exotica', 'Nativa e Exótica')
    )
    
    square = models.ForeignKey(Square, related_name="trees", on_delete=models.CASCADE)#Category
    name = models.CharField('Nome popular', max_length=255) 
    specie = models.ForeignKey(Specie, related_name="species", on_delete=models.CASCADE) #implementado
    family = models.ForeignKey(Family, related_name="family", on_delete=models.CASCADE) #implementado
    source = models.CharField('Origem', max_length=20, choices=SOURCE_CHOICES)
    description = models.TextField('Descrição', blank=True)
    is_display = models.BooleanField('Exibir', default=True)
    image1 = models.ImageField('imagem 1', upload_to=get_file_path, blank=True)
    altimg1 = models.CharField('Alt imagem 1', max_length=150, blank=True)#modificado original não tem 'imagem'
    image2 = models.ImageField('imagem 2', upload_to=get_file_path, blank=True)
    altimg2 = models.CharField('Alt imagem 2', max_length=150, blank=True)#implementado
    image3 = models.ImageField('imagem 3', upload_to=get_file_path, blank=True)
    altimg3 = models.CharField('Alt imagem 3', max_length=150, blank=True)#implementado
    quantidade = models.PositiveIntegerField(default=1,null=False, blank=False)
  
    
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    
   

    objects = models.Manager()
    display = DisplayManager()

    class Meta:
        ordering = ("name",)
        verbose_name = "Árvore"
        verbose_name_plural = "Árvores"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("trees:detail", kwargs={"slug": self.slug})

users/models.py
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    pass

users/forms.py
from django.contrib.auth import forms

from .models import User


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User

pages/views.py
from django.views.generic import TemplateView
from trees.models import Square


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['square'] = Square.objects.all() #ordem aleatória
        return context


class AboutPageView(TemplateView):
    template_name = "about.html"

    

trees/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView 



from .models import Square, Tree


class TreeDetailView(DetailView):
    queryset = Tree.display.all()
    


class TreeListView(ListView):
    square = None
    paginate_by = 6 #mudar para 4 depois

    def get_queryset(self):
        queryset = Tree.display.all()

        
        square_slug = self.kwargs.get("slug")
        if square_slug:
            self.square = get_object_or_404(Square, slug=square_slug)
            queryset = queryset.filter(square=self.square)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["square"] = self.square
        context["squaries"] = Square.display.all()
        return context

users/views.py
from django.shortcuts import render

# Create your views here.

templates/about.html
{% load static %}
<section id="about" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-12 col-xs-12 info">
          <div class="about-wrapper wow fadeInLeft" data-wow-delay="0.3s">
            <div>
              <div class="site-heading">
                <h2 class="section-title">Projeto Integrador II</h2>
              </div>
              <div class="content">
                <p>

                </p>O Projeto Integrador é uma atividade curricular que consiste na resolução de um problema real contextualizado na profissão em que o curso está inserido.​Em grupo, os estudantes devem delimitar um problema a partir do tema norteador da disciplina, propondo uma solução aplicável, usando os conhecimentos estudados nas disciplinas cursadas até o momento. ​ Ao longo do semestre os alunos terão autonomia de aprendizagem no que tange à pesquisa, organização e desenvolvimento do projeto, com suportes e acompanhamentos semanais do orientador de PI.​ 
                As metodologias de ensino-aprendizagempressupõe<br>Trabalho coletivo e colaborativo;<br>Aprendizagem ativa;<br>Identificação de problemas em contextos reais;<br>
Empatia para busca por soluções centradas no ser humano.
              <div class="row">
                <div class="col-lg-6">
                </p>
                <a href="#hero-area" class="btn btn-common mt-3">Página Inicial</a> 

                </div> 
                <div class="col-lg-6">
                </p>
                <a href="#members" class="btn btn-common mt-3">Membros</a> 


                </div>
                
              </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 col-xs-12 wow fadeInRight" data-wow-delay="0.3s">
          <img class="img-fluid" src="{% static 'img/about/img-1.png' %}" alt="Imagem ilustrando o grupo do Projeto Integrador em uma reunião" >
        </div>
      </div>
    </div>
  </section>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Arvorização de Monte Alto</title>

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico'%}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Icon -->
    <link rel="stylesheet" href="{% static 'fonts/line-icons.css' %}">
    <!-- Owl carousel -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css2' %}">
    
    <!-- Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Main Style -->

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.13.0/css/all.css">
  </head>
  <body>

    <!-- Header Area wrapper Starts -->
    <header id="header-wrap">
      <!-- Navbar Start -->
      <nav class="navbar navbar-expand-md bg-inverse fixed-top scrolling-navbar">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a href="{% url 'pages:home' %}" class="navbar-brand"><img src="{% static 'img/logo.png' %}" alt="Braão de Monte Alto"></a>       
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end clearfix">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:home' %}" ><i class="fas fa-home"> </i>
                  Home
                </a>
                </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'trees:list' %}"><i class="fad fa-trees"> </i>Espécies</a>

                <li class="nav-item">
                  <a class="nav-link" href="#about"><i class="fas fa-users"></i> Sobre Nós</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}"><i class="fad fa-user-cog"></i> Administração</a>
                </li>
             
              <li class="nav-item">
                <div class="btn-container">
                  <button name="increase-font" id="increase-font" title="Aumentar fonte">A +</button>
                  <button name="decrease-font" id="decrease-font" title="Diminuir fonte">A -</button>
              </div>
              </li>
              <li class="nav-item">
              
           
        </li>
            </ul>
          </div>
        </div>
      </nav>
      
      <!-- Navbar End -->
      {% block content %}  {% endblock %}
    <!-- Go to Top Link -->
    <a href="#" class="back-to-top">
    	<i class="lni-arrow-up"></i>
    </a>
    
    <!-- Preloader -->
    <div id="preloader">
      <div class="loader" id="loader-1"></div>
    </div>
    <!-- End Preloader -->
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/wow.js' %}"></script>
    <script src="{% static 'js/jquery.nav.js' %}"></script>
    <script src="{% static 'js/scrolling-nav.js' %}"></script>
    <script src="{% static '/js/jquery.easing.min.js' %}"></script>  
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/form-validator.min.js' %}"></script>
    <script src="{% static 'js/contact-form-script.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cookie.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/script-acessib.js' %}"></script>
    <script src="{% static 'js/script-weather.js' %}"></script>
    
      
  </body>
</html>

templates/footer.html
{% load static %}
<footer id="footer" class="footer-area section-padding">
    <div class="container">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
 
  
            </div>
          </div>
        

        </div>
      </div>  
    </div> 
    <div id="copyright">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright-content">
              <p>Copyright © 20222 <a rel="nofollow" href="#"></a> All Right Reserved</p>
            </div>
          </div>
        </div>
      </div>
    </div>   
  </footer> 

templates/hero.html
{% load static %}
<section id="hero-area" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
          <div class="about-wrapper wow fadeInLeft" data-wow-delay="0.3s">
            <div>
              <div class="site-heading mt-0 ">
                <h2>Diversidade Arbória</h2><h3> Praças de Monte Alto - SP.</h3>
              </div>
              <div class="content" style="background-color: rgb(255, 255, 255);">
                <p>

                </p>A arborização das praças da cidade de Monte Alto – SP constitui uma paisagem diversificada, tendo várias espécies arbóreas compondo sua estrutura, sendo importante para a purificação do ar, e mantendo a temperatura do ambiente agradável, levando vários cidadãos a visitá-las por ter estas características.<br>Projeto desenvolvido por alunos da UNIVESP - Grupo 049 - Turma 002
                
              </div>
            </p>
            <a href="#about" class="btn btn-common mt-3">Maiores informações</a> 
            </div>
          </div>
          
        </div>
    
        </div>
      </div>
    </div>
  </section>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Hero Area Start -->
    {% include 'hero.html' %}
    <!-- Hero Area End -->
 
    <!-- About Section start -->
    {% include 'about.html' %}
    <!-- About Section End -->


    <!-- Features Section Start -->
    {% include 'members.html' %}
    <!-- Features Section End -->   
   
    <!-- Footer Section Start -->
    {% include 'footer.html' %}
    <!-- Footer Section End -->
    {% endblock %}
   

templates/members.html
{% load static %}
<section id="members" class="section-padding">
    <div class="container">
      <div class="section-header text-center">          
        <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Membros e Formadores do Projeto Integrador II</h2>
        <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12"><!--1-->
          <div class="content-right">
            <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
               <div class="text">
                <h4>Adilson Teixeira Lima</h4>
                <p></p>
              </div>
            </div >
            <div class="content-right">
            <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
               <div class="text">
                <h4>Charles Roberto Alegre</h4>
                <p></p>
              </div>
             </div>
             <div class="content-right">
             <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
              <div class="text">
               <h4>Éder Matheus Pereira</h4>
               <p></p>
             </div>
            </div>
           </div>
           <div class="content-right">
            <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
             <div class="text">
              <h4>Herick Hamada</h4>
              <p></p>
            </div>
           </div>
          </div>

        </div>
        </div>
        </div><!--final coluna-->
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12"><!--1-->
          <div class="content-right">
            <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
               <div class="text">
                <h4>Kleber Juliano Aleixo</h4>
                <p></p>
              </div>
            </div >
            <div class="content-right">
            <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
               <div class="text">
                <h4>Manoel Alípio de Sant’Ana</h4>
                <p></p>
              </div>
             </div>
             <div class="content-right">
             <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
              <div class="text">
               <h4>Paulo Sérgio Fumes</h4>
               <p></p>
             </div>
            </div>
           </div>
           <div class="content-right">
            <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
             <div class="text">
              <h4>Wagner José da Silva</h4>
              <p></p>
            </div>
           </div>
          </div>

        </div>
        
        </div>
        </div><!--final coluna-->
        <div class="col-lg-4 col-md-8 col-sm-8 col-xs-">
        <div class="content-right">
          <div class="box-item wow fadeInLeft" data-wow-delay="0.6s"><!--2-->
            <div class="text">
            <p>Professores Autores da disciplina</p>
            <h4>Prof. Dr. Marcelo Garcia Manzato</h4>
            <h4>Profª. Dra. Mônica Cristina Garbin</h4>
            <p>Orientadora</p>
            <h4>Profª. Adriana Andrade</h4>
           </div>
           <div class="wow fadeInRight" data-wow-delay="0.3s">
            <img class="img-fluid width: 50%" src="{% static 'img/thumb-univesp.jpg' %}" alt="Logo da UNIVESP" >
          </div>
           
           </div>
         </div>
        </div>

      </div> <!-- fim da row-->
    </div>
  </section>

templates/pagination.html
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    Página {{ page.number }} de {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Próxima</a>
    {% endif %}
</div>

templates/products/product_list.html
{% extends 'base.html' %}

{% load static %}
{% load product_tags %}

{% block title %}
{% if category %}
{{ category.name }}
{% else %}
Produtos
{% endif %}
{% endblock title %}

{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-lg-3">
            <ul class="list-group mb-3 mb-lg-0">
                <a class="text-decoration-none list-group-item list-group-item-light {% if not category %}active{% endif %}"
                    href="{% url 'products:list' %}">
                    Todos os produtos
                </a>

                {% for cat in categories %}
                <a class="text-decoration-none list-group-item list-group-item-light {% if category == cat %}active{% endif %}"
                    href="{{ cat.get_absolute_url }}">
                    {{ cat.name }}
                </a>
                {% endfor %}
            </ul>
        </div>
        <div class="col-lg-9">
            <div class="card-deck mb-3">
                {% for product in product_list %}
                <div class="card">
                    <a href="{{ product.get_absolute_url }}">
                        {% if product.image %}
                        <img class="card-img-top" src="/media/{{product.image}}" alt="">
                        {% else %}
                        <img class="card-img-top" src="{% static 'images/no_image.jpg' %}" alt="">
                        {% endif %}
                    </a>

                    <div class="card-body d-flex flex-column justify-content-between">
                        <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                            <h5 class="card-title">{{ product.name }}</h5>
                        </a>
                        <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">
                            <p class="card-text font-weight-bold">R$ {{ product.price }}</p>
                        </a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div>
            <div class="card-deck mb-3">
                {% endif %}
                {% endfor %}

                {% if product_list|length|remainder == 2 %}
                <div class="card border-0"></div>
                {% elif product_list|length|remainder == 1 %}
                <div class="card border-0"></div>
                <div class="card border-0"></div>
                {% endif %}
            </div>

            {% if is_paginated %}
            {% include "pagination.html" with page=page_obj %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/temperatura.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style_weather.css' %}"/>
  <title>Weather</title>
</head>

<body>
  <div class="container-fluid p-0 container-sm d-flex justify-content-center">

    <div class="card text-center shadow-lg" style="width: 26rem;">

      <div class="card-header bg-white text-dark font-weight-bold">
        TEMPO E TEMPERATURA
      </div>
        <div class="card-body">
          <div class="city">Monte Alto - SP</div>
          <div class="date">Terça, 1 Dezembro 2020</div>
          <div class="container-img">

            <img src="{% static 'icons/unknown.png' %}">
          </div>
          <div class="container-temp mx-2 my-3">
            <div>22</div>
            <span>°c</span>
          </div>
          <div class="weather py-2">Nublado</div>
          <div class="humid"> Humidade: <strong><span class="humidit">50%</span></strong></div>
          
      </div>

    
    </div>

    </div>
  <script src="{% static 'js/script-weather.js' %}"></script>
  
  <script src="https://kit.fontawesome.com/f0e17cbf2f.js" crossorigin="anonymous"></script>
</body>

</html>

templates/trees/tree_list.html
{% extends 'base.html' %}

{% load static %}
{% load trees_tags %}

{% block title %}
{% if squarie %}
{{ square.name }}
{% else %}
  Tree
{% endif %}
{% endblock title %}

{% block content %}
<section id="tree" class="section-padding">  
<div class="container-fluid"valign="top"> <!--my-3-->
    
    <div class="row" valign="top"><!--row-->
        <div class="col-lg-2">
            
            <div class="section-header text-center mb-8" >          
                <h2 class="section-title wow fadeInDown mb-4" data-wow-delay="0.3s">Praças de Monte Alto</h2>
             
            </div>
            <ul class="list-group mb-3 mb-lg-8">
                <a class="text-decoration-none list-group-item list-group-item-light {% if not square %}active{% endif %}"
                    href="{% url 'trees:list' %}">
                    Todos as praças
                </a>

                {% for praca in squaries %}
                <a class="text-decoration-none list-group-item list-group-item-light {% if square == praca %}active{% endif %}"
                    href="{{ praca.get_absolute_url }}">
                    {{ praca.name }}
                </a>
                {% endfor %}
            </ul>
            
            <div class="section-header text-center">
                {% if is_paginated %}
            {% include "pagination.html" with page=page_obj %}
            {% endif %}
            </div>
        </div>
       
        <!--fim col-lg-3-->
   
        <div class="col-lg-10">
                            
            <div class="row" valign="top">
            {% for tree in tree_list %}
            <div class="col-lg-6 col-md-6 col-xs-6">
                <a class="text-decoration-none text-dark" href="#modal{{ tree.slug }}"data-toggle="modal">   
            <div class="card" valign="top">
            
                <div class="tree-item wow fadeInRight" data-wow-delay="0.8s">
                    <div class="tree-img"><img class="card-img-top" src="/media/{{tree.image1}}" alt="{{ tree.altimg1 }}">
                    </div>   
                <div class="contetn">
                    <div class="info-text">
                        <a class="info-text" href="#modal{{ tree.slug }}"data-toggle="modal"><h3>{{ tree.name }}</a></h3>
                    <p><strong>Família: </strong>{{ tree.family }}</strong></p><br>
                    <p><a class="info-text" href="#modalpraca{{ tree.slug }}"data-toggle="modal"><strong>{{ tree.square }}</strong></p>
                    </div></a>
                    
                    
                </div>
               
                </div>
            </div>
        </div>
        <!-- Modal 1 -->
            <div class="modal fade bd-example-modal-lg" id="modal{{ tree.slug }}"  role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <a class="text-decoration-none text-dark" href="#modal{{ tree.slug }}"data-toggle="modal"></a><h3 class="font-weight-bold">{{ tree.name }}</h3>
                            
                            
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        
                        
                        <div class="col-lg-12">
                            <h2>{{tree.especie}}</h2>
                            <p>Família: <strong>{{tree.family}}</strong></p>
                            <p>Origem: <strong>{{tree.source}}</strong></p>
                        
                        </div>
                       
                        <div class="modal-body">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-6 col-md-6 ">
                                    <img class="img-fluid " src="/media/{{tree.image2}}" alt="{{ tree.altimg2 }}">
                                    </div>
                                    <div class="col-6 col-md-6">
                                    <img class="img-fluid " src="/media/{{tree.image3}}" alt="{{ tree.altimg3 }}">
                                    </div>
                                    <div class="col-lg-12">
                                     <p><br></p>
                                    <p>{{ tree.description }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!--final modal-->
        <!-- Modal 1 -->
        <div class="modal fade bd-example-modal-lg" id="modalpraca{{ tree.slug }}"  role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <a class="text-decoration-none text-dark" href="#modal{{ tree.slug }}"data-toggle="modal"></a><h3 class="font-weight-bold">{{ tree.square.name }}</h3><br>
                        
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                   
                    <div class="modal-body">
                          <div class="container-fluid md-4">
                            <div class="row">
                                <div class="col-6 col-md-6 ">
                                <img class="img-fluid " src="/media/{{tree.square.image1}}" alt="{{ tree.square.altimg1 }}">
                                </div>
                                <div class="col-6 col-md-6">
                                <img class="img-fluid " src="/media/{{tree.square.image2}}" alt="{{ tree.square.altimg2 }}">
                                </div>
                                <div class="col-lg-12">
                                    <br>
                                   <p><strong>{{tree.square.address}}</strong></p><br>
                                    <p></p>
                                <p>{{ tree.description }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!--final modal-->
        {% endfor %}
    </div>
               <!-- % if forloop.counter|divisibleby:"3" and not forloop.last %
           
            <div class="card-deck mb-3">
                % endif %
             

                % if tree_list|length|remainder == 2 %
                <div class="card border-0"></div>
                % elif tree_list|length|remainder == 1 %
                <div class="card border-0"></div>
                <div class="card border-0"></div>
                % endif %
            </div>-->

            
        </div>
    </div>
</div> <!--final container-->
</section>
{% endblock content %}